name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version for which the formula will be generated
        required: true
      sha256:
        description: The sha256 of the tuist.zip file associated to the version
        required: true

permissions:
  contents: write

env:
  MISE_EXPERIMENTAL: 1

jobs:
  release:
    name: Release
    runs-on: 'blacksmith-4vcpu-ubuntu-2204'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: jdx/mise-action@v2
      - name: Generate formula
        run: |
          mise run release -- -v ${{ github.event.inputs.version }} -s ${{ github.event.inputs.sha256 }}
      - name: Update @latest aliases
        run: |
          mise run aliases
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Release ${{ github.event.inputs.version }}"
